# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = r'C:\Users\bhava\Documents\18.02.26_Instacart Basket Analysis'

In [3]:
df_orders_products_combined = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_combined.pkl'))

In [4]:
df_products = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'products_checked.csv'), index_col = False)

In [5]:
df_products.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices
0,0,1,Chocolate Sandwich Cookies,61,19,5.8
1,1,2,All-Seasons Salt,104,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,4,5,Green Chile Anytime Sauce,5,13,4.3

In [6]:
df_products.shape

(49672, 6)

In [7]:
# 3. Dataframe -- is the same as previous dataframe

df_orders_products_combined.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,NaN,196,1,0,both
1,2539329,1,1,2,8,NaN,14084,2,0,both
2,2539329,1,1,2,8,NaN,12427,3,0,both
3,2539329,1,1,2,8,NaN,26088,4,0,both
4,2539329,1,1,2,8,NaN,26405,5,0,both

In [8]:
# 4. Shape -- is the same as previous dataframe

df_orders_products_combined.shape

(32434489, 10)

# 5. Merging Data

In [9]:
print(df_orders_products_combined.columns)
print(df_products.columns)

Index(['order_id', 'user_id', 'order_number', 'order_day_of_week',
       'order_hour_of_day', 'days_since_last_order', 'product_id',
       'add_to_cart_order', 'reordered', '_merge'],
      dtype='object')
Index(['Unnamed: 0', 'product_id', 'product_name', 'aisle_id', 'department_id',
       'prices'],
      dtype='object')

In [10]:
print(df_orders_products_combined['product_id'].dtype)
print(df_products['product_id'].dtype)

int64
int64

In [11]:
df_orders_products_combined = df_orders_products_combined.drop(columns=['_merge'], errors='ignore')
df_products = df_products.drop(columns=['_merge'], errors='ignore')

In [12]:
df_ords_prods_merge = df_orders_products_combined.merge(df_products, on='product_id', how='inner', indicator=True)

In [13]:
df_ords_prods_merge.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both
1,2539329,1,1,2,8,NaN,14084,2,0,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,1,2,8,NaN,12427,3,0,12427,Original Beef Jerky,23,19,4.4,both
3,2539329,1,1,2,8,NaN,26088,4,0,26089,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,1,2,8,NaN,26405,5,0,26406,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

# 6. Merge Flag

In [14]:
df_ords_prods_merge['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

# 7. Export

In [16]:
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge.pkl'))